# This file is just here to make tests pass when run from inside this gem directory.
# Seems like maybe we need a better resolution method for this file?
default:
  models:
    Team: read
    Document: read
    Membership:
      - read
      - search

crud_role:
  models:
    Team: crud

editor:
  models:
    Scaffolding::AbsolutelyAbstract::CreativeConcept:
      - read
      - update

manager:
  includes:
    - editor

supervisor:
  includes:
    - manager

admin:
  includes:
    - editor
  manageable_roles:
    - admin
    - editor
  models:
    Team: manage
    Membership: manage
    Document: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept: manage
