# This is a default implementation of this file that we supply to help with gem tests.
# The version from the starter repo will take precedence when running the full app.
# You can think of the file in the starter repo as having been ejected from this gem.

# This file is here just to allow tests to pass when run from inside this gem directory.
# It wasn't found if I put the file in test/dummy/config/models/webhooks/outgoing, so
# maybe we need a better resolution method?
scaffolding/absolutely_abstract/creative_concept:
  # This automatically generates `created`, `updated`, and `deleted` webhook events.
  - crud
scaffolding/completely_concrete/tangible_thing:
  - crud
invitation:
  - crud
membership:
  - crud
